<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5yscvla\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5yscvla/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5yscvla.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5yscvla\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5yscvla\appProdProjectContainer([
    'container.build_hash' => '5yscvla',
    'container.build_id' => '4d52b36c',
    'container.build_time' => 1566420021,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5yscvla');
